http:
  port: "8081"
  
american:
  host: "training4-american-api-delacerna.cloudhub.io" 
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"

  